# A11y Agent Team - Update Script (Windows PowerShell)
# Built by Taylor Arndt - https://github.com/taylorarndt
#
# Checks for updates from GitHub and installs them.
# Can be run manually or automatically via Scheduled Task.
#
# Usage:
#   powershell -File update.ps1              Update global install
#   powershell -File update.ps1 -Project     Update project install
#   powershell -File update.ps1 -Silent      Suppress output (for scheduled runs)

param(
    [switch]$Project,
    [switch]$Silent
)

$ErrorActionPreference = "Stop"

$RepoUrl = "https://github.com/Community-Access/accessibility-agents.git"
$CacheDir = Join-Path $env:USERPROFILE ".claude\.a11y-agent-team-repo"
$VersionFile = Join-Path $env:USERPROFILE ".claude\.a11y-agent-team-version"
$LogFile = Join-Path $env:USERPROFILE ".claude\.a11y-agent-team-update.log"

# Agents are auto-detected from the cached repo after clone/pull

function Write-Log {
    param([string]$Message)
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $Entry = "[$Timestamp] $Message"
    Add-Content -Path $LogFile -Value $Entry
    if (-not $Silent) {
        Write-Host "  $Message"
    }
}

if ($Project) {
    $InstallDir = Join-Path (Get-Location) ".claude"
} else {
    $InstallDir = Join-Path $env:USERPROFILE ".claude"
}

# Check for git
try {
    git --version | Out-Null
} catch {
    Write-Log "Error: git is not installed. Cannot check for updates."
    exit 1
}

# Clone or pull the repo
$GitDir = Join-Path $CacheDir ".git"
if (Test-Path $GitDir) {
    Set-Location $CacheDir
    git fetch origin main --quiet 2>$null
    $LocalHash = git rev-parse HEAD 2>$null
    $RemoteHash = git rev-parse origin/main 2>$null

    if ($LocalHash -eq $RemoteHash) {
        Write-Log "Already up to date."
        exit 0
    }

    git reset --hard origin/main --quiet 2>$null
    Write-Log "Pulled latest changes."
} else {
    Write-Log "Downloading a11y-agent-team..."
    $ParentDir = Split-Path $CacheDir -Parent
    New-Item -ItemType Directory -Force -Path $ParentDir | Out-Null
    git clone --quiet $RepoUrl $CacheDir 2>$null
    Write-Log "Repository cloned."
}

Set-Location $CacheDir
$NewHash = git rev-parse --short HEAD 2>$null

# ---------------------------------------------------------------------------
# Merge-ConfigFile: update our marked section; never overwrites user content
# ---------------------------------------------------------------------------
function Merge-ConfigFile {
    param([string]$SrcFile, [string]$DstFile, [string]$Label)
    $start  = "<!-- a11y-agent-team: start -->"
    $end    = "<!-- a11y-agent-team: end -->"
    $body   = ([IO.File]::ReadAllText($SrcFile, [Text.Encoding]::UTF8)).TrimEnd()
    $block  = "$start`n$body`n$end"
    if (-not (Test-Path $DstFile)) {
        [IO.File]::WriteAllText($DstFile, "$block`n", [Text.Encoding]::UTF8)
        Write-Log "Created: $Label"
        $script:Updated++
        return
    }
    $existing = [IO.File]::ReadAllText($DstFile, [Text.Encoding]::UTF8)
    if ($existing -match [regex]::Escape($start)) {
        $pattern = "(?s)" + [regex]::Escape($start) + ".*?" + [regex]::Escape($end)
        $updated = [regex]::Replace($existing, $pattern, $block)
        if ($updated -ne $existing) {
            [IO.File]::WriteAllText($DstFile, $updated, [Text.Encoding]::UTF8)
            Write-Log "Updated section: $Label"
            $script:Updated++
        }
    } else {
        [IO.File]::WriteAllText($DstFile, $existing.TrimEnd() + "`n`n$block`n", [Text.Encoding]::UTF8)
        Write-Log "Merged section: $Label"
        $script:Updated++
    }
}

# Load manifest — only update files we installed; never touch user-created files
$ManifestPath = Join-Path $InstallDir ".a11y-agent-manifest"
$Manifest = @{}
if (Test-Path $ManifestPath) {
    [IO.File]::ReadAllLines($ManifestPath, [Text.Encoding]::UTF8) | ForEach-Object { $Manifest[$_] = $true }
}
# If local manifest is empty (lost/new install), seed it from the repo-level manifest
# generated by CI so we know which agents are official vs user-created.
if ($Manifest.Count -eq 0) {
    $RepoManifest = Join-Path $CacheDir ".a11y-agent-manifest"
    if (Test-Path $RepoManifest) {
        [IO.File]::ReadAllLines($RepoManifest, [Text.Encoding]::UTF8) | ForEach-Object {
            $line = $_.Trim()
            if ($line -ne '') { $Manifest[$line] = $true }
        }
        Write-Log "Seeded local manifest from repo ($($Manifest.Count) entries)."
    }
}

# Auto-detect and update agents — only update files we installed (in manifest)
# Never delete files: they might be user-created agents
$Updated = 0
$AgentsSrcDir = Join-Path $CacheDir ".claude\agents"
if (Test-Path $AgentsSrcDir) {
    foreach ($File in Get-ChildItem -Path $AgentsSrcDir -Filter "*.md") {
        $Dst = Join-Path $InstallDir "agents\$($File.Name)"
        $manifestKey = "agents/$($File.Name)"
        # Only update if: file is in our manifest OR doesn't exist yet (new agent)
        if (-not (Test-Path $Dst)) {
            Copy-Item -Path $File.FullName -Destination $Dst
            $Manifest[$manifestKey] = $true   # track for future updates
            Write-Log "Added (new): $($File.BaseName)"
            $Updated++
        } elseif ($Manifest.ContainsKey($manifestKey)) {
            $SrcContent = Get-Content $File.FullName -Raw -ErrorAction SilentlyContinue
            $DstContent = Get-Content $Dst -Raw -ErrorAction SilentlyContinue
            if ($SrcContent -ne $DstContent) {
                Copy-Item -Path $File.FullName -Destination $Dst -Force
                Write-Log "Updated: $($File.BaseName)"
                $Updated++
            }
        }
        # Files not in manifest and already present are skipped (user files)
    }
}
# Save manifest — new agents contributed to the repo are tracked for future updates
[IO.File]::WriteAllLines($ManifestPath, ($Manifest.Keys | Sort-Object), [Text.Encoding]::UTF8)

# Helper: recursively sync a source directory to a destination directory.
# Updates changed files and adds new files.
# Does NOT remove files: they might be user-created files in the same directory.
function Sync-GitHubDir {
    param([string]$SrcDir, [string]$DstDir, [string]$Label)
    if (-not (Test-Path $SrcDir)) { return }
    if (-not (Test-Path $DstDir)) { return }  # only sync if previously installed
    foreach ($File in Get-ChildItem -Recurse -File $SrcDir) {
        $Rel = $File.FullName.Substring($SrcDir.Length).TrimStart('\')
        $Dst = Join-Path $DstDir $Rel
        New-Item -ItemType Directory -Force -Path (Split-Path $Dst) | Out-Null
        $SrcContent = Get-Content $File.FullName -Raw -ErrorAction SilentlyContinue
        $DstContent = Get-Content $Dst -Raw -ErrorAction SilentlyContinue
        if ($SrcContent -ne $DstContent) {
            Copy-Item -Path $File.FullName -Destination $Dst -Force
            Write-Log "Updated $Label\$Rel"
            $script:Updated++
        }
    }
}

$GitHubSrc = Join-Path $CacheDir ".github"

# Update Copilot assets for project install
if ($Project) {
    $ProjectRoot = (Get-Location).Path
    $ProjectGitHub = Join-Path $ProjectRoot ".github"
    if (Test-Path $ProjectGitHub) {
        # Agents (all files: *.agent.md + AGENTS.md, shared-instructions.md, etc.)
        Sync-GitHubDir -SrcDir (Join-Path $GitHubSrc "agents") -DstDir (Join-Path $ProjectGitHub "agents") -Label "agents"
        # Config files — merged to preserve user content above/below our section
        foreach ($Config in @("copilot-instructions.md", "copilot-review-instructions.md", "copilot-commit-message-instructions.md")) {
            $Src = Join-Path $GitHubSrc $Config
            $Dst = Join-Path $ProjectGitHub $Config
            if (Test-Path $Src) {
                Merge-ConfigFile -SrcFile $Src -DstFile $Dst -Label "Copilot config: $Config"
            }
        }
        # Asset subdirs: skills, instructions, prompts
        foreach ($SubDir in @("skills", "instructions", "prompts")) {
            Sync-GitHubDir -SrcDir (Join-Path $GitHubSrc $SubDir) -DstDir (Join-Path $ProjectGitHub $SubDir) -Label $SubDir
        }
    }
}

# Update Copilot assets for global install
if (-not $Project) {
    $CentralRoot   = Join-Path $env:USERPROFILE ".a11y-agent-team"
    $Central       = Join-Path $CentralRoot "copilot-agents"
    $CentralPrompts      = Join-Path $CentralRoot "copilot-prompts"
    $CentralInstructions = Join-Path $CentralRoot "copilot-instructions-files"
    $CentralSkills       = Join-Path $CentralRoot "copilot-skills"

    # Update central stores (agents, prompts, instructions, skills)
    if (Test-Path $Central) {
        foreach ($File in Get-ChildItem -Path (Join-Path $GitHubSrc "agents") -Filter "*.agent.md" -ErrorAction SilentlyContinue) {
            $Dst = Join-Path $Central $File.Name
            $SrcContent = Get-Content $File.FullName -Raw -ErrorAction SilentlyContinue
            $DstContent = Get-Content $Dst -Raw -ErrorAction SilentlyContinue
            if ($SrcContent -ne $DstContent) {
                Copy-Item -Path $File.FullName -Destination $Dst -Force
                Write-Log "Updated central agent: $($File.BaseName)"
                $Updated++
            }
        }
    }
    if (Test-Path $CentralPrompts)      { Sync-GitHubDir -SrcDir (Join-Path $GitHubSrc "prompts")      -DstDir $CentralPrompts      -Label "central-prompts" }
    if (Test-Path $CentralInstructions) { Sync-GitHubDir -SrcDir (Join-Path $GitHubSrc "instructions") -DstDir $CentralInstructions -Label "central-instructions" }
    if (Test-Path $CentralSkills)       { Sync-GitHubDir -SrcDir (Join-Path $GitHubSrc "skills")       -DstDir $CentralSkills       -Label "central-skills" }
    # Update config files in central store — merged to preserve user content
    foreach ($Config in @("copilot-instructions.md", "copilot-review-instructions.md", "copilot-commit-message-instructions.md")) {
        $Src = Join-Path $GitHubSrc $Config
        $Dst = Join-Path $CentralRoot $Config
        if (Test-Path $Src) {
            Merge-ConfigFile -SrcFile $Src -DstFile $Dst -Label "Copilot config: $Config"
        }
    }

    # Push agents, prompts, and instructions to VS Code User profile folders.
    # VS Code 1.110+ discovers from User/prompts/; older from User/ root. Both are updated.
    $VSCodeProfiles = @(
        (Join-Path $env:APPDATA "Code\User"),
        (Join-Path $env:APPDATA "Code - Insiders\User")
    )
    foreach ($ProfileDir in $VSCodeProfiles) {
        $PromptsDir = Join-Path $ProfileDir "prompts"
        # Only update if agents were previously installed
        $HasAgents = (Get-ChildItem -Path $ProfileDir -Filter "*.agent.md" -ErrorAction SilentlyContinue).Count -gt 0
        $HasPrompts = (Test-Path $PromptsDir) -and ((Get-ChildItem -Path $PromptsDir -Filter "*.agent.md" -ErrorAction SilentlyContinue).Count -gt 0)
        if (-not ($HasAgents -or $HasPrompts)) { continue }
        New-Item -ItemType Directory -Force -Path $PromptsDir | Out-Null
        foreach ($File in Get-ChildItem -Path $Central -Filter "*.agent.md" -ErrorAction SilentlyContinue) {
            Copy-Item -Path $File.FullName -Destination (Join-Path $ProfileDir $File.Name) -Force
            Copy-Item -Path $File.FullName -Destination (Join-Path $PromptsDir $File.Name) -Force
        }
        foreach ($File in Get-ChildItem -Path $CentralPrompts -Filter "*.prompt.md" -ErrorAction SilentlyContinue) {
            Copy-Item -Path $File.FullName -Destination (Join-Path $ProfileDir $File.Name) -Force
            Copy-Item -Path $File.FullName -Destination (Join-Path $PromptsDir $File.Name) -Force
        }
        foreach ($File in Get-ChildItem -Path $CentralInstructions -Filter "*.instructions.md" -ErrorAction SilentlyContinue) {
            Copy-Item -Path $File.FullName -Destination (Join-Path $ProfileDir $File.Name) -Force
            Copy-Item -Path $File.FullName -Destination (Join-Path $PromptsDir $File.Name) -Force
        }
        Write-Log "Updated VS Code profile: $ProfileDir"
    }
}

# Update enforcement hooks (global install only)
if (-not $Project) {
    $HooksDir = Join-Path $env:USERPROFILE ".claude\hooks"
    $HookSrcDir = Join-Path $CacheDir "claude-code-plugin\scripts"
    if ((Test-Path $HooksDir) -and (Test-Path $HookSrcDir)) {
        foreach ($Hook in @("a11y-team-eval.sh", "a11y-enforce-edit.sh", "a11y-mark-reviewed.sh")) {
            $Src = Join-Path $HookSrcDir $Hook
            $Dst = Join-Path $HooksDir $Hook
            if (Test-Path $Src) {
                if (-not (Test-Path $Dst)) {
                    Copy-Item -Path $Src -Destination $Dst -Force
                    Write-Log "Added hook (new): $Hook"
                    $Updated++
                } else {
                    $SrcContent = Get-Content $Src -Raw -ErrorAction SilentlyContinue
                    $DstContent = Get-Content $Dst -Raw -ErrorAction SilentlyContinue
                    if ($SrcContent -ne $DstContent) {
                        Copy-Item -Path $Src -Destination $Dst -Force
                        Write-Log "Updated hook: $Hook"
                        $Updated++
                    }
                }
            }
        }
    }
}

# Save version
$NewHash | Out-File -FilePath $VersionFile -Encoding utf8 -NoNewline

if ($Updated -gt 0) {
    Write-Log "Update complete ($Updated files updated, version $NewHash)."
} else {
    Write-Log "Files already match latest version ($NewHash)."
}
